### ISSUE TITLE
Training workflows

### ISSUE THREAD

**Issue by pwalczysko** [ome/design#76]
@jburel @sbesson @bramalingam @joshmoore 

This is an issue trying to come up with the

  - workflow for reviewing the OME-workflows used in workshops and trainings but also offered publicly for others to do their workshops or training with
  - the workflows should be public, so the place for the PR could be:

    - https://github.com/openmicroscopy/ome-help subdirectory ?
    - new public repo

The first prototype is on https://github.com/openmicroscopy/ome-internal/issues/350

Mid-term, there are planned are some 3 more workflows, in prep of the workshop in Cambridge.

**Comment by pwalczysko** [comment]
@hflynn

**Comment by hflynn** [comment]
Do we know what format we want to supply these materials in? Let's not have yet another repo if we can help it!

**Comment by jburel** [comment]
depending on how we want to use them but powerpoint might be the most re-usable option

**Comment by joshmoore** [comment]
I'd add though that we should manage (incl. versioning) the images independently of PowerPoint so we can share with revealjs, jupyter notebooks, etc.

**Comment by jburel** [comment]
we will need to have a well established workflow since the "sharing" has not work so well so far.
We have more a copy/paste of images between repo

**Comment by jburel** [comment]
We have now created many guides describing those workflows
